//  Copyright 2023 Semenova Veronika

#ifndef MODULES_BINARY_TREE_INCLUDE_BINARY_TREE_H_
#define MODULES_BINARY_TREE_INCLUDE_BINARY_TREE_H_

struct Node {};

#endif  //  MODULES_BINARY_TREE_INCLUDE_BINARY_TREE_H_
